Issue DP-40 - Run tests in CI
This adds 2 more testing stages to the pipeline.
Firstly some simple unit tests with gradle and
secondly by running the test APKs on testobject.

Any test failures will fail the pipeline and all results
are published via gitlab (using junit formatted XML files)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,7 @@
 stages:
+  - unit_test
   - build
+  - device_tests
   - publish
 
 .job_template: &common_build_all
@@ -16,6 +18,14 @@ stages:
     - make TARGET_OS=android ABP_TARGET_ARCH=ia32 Configuration=release get-prebuilt-v8
     - make TARGET_OS=android ABP_TARGET_ARCH=ia32 Configuration=release
     - cd ..
+
+gradle_unit_tests:
+  stage: unit_test
+  script:
+    - ./gradlew test
+  artifacts:
+    reports:
+      junit: adblock-android/build/test-results/*/TEST-*.xml
 
 build_libadblockplus-android:arm:
   stage: build
@@ -63,11 +73,13 @@ build_libadblockplus-android:all:
   <<: *common_build_all
   stage: build
   script:
-    - ./gradlew clean assemble
+    - ./gradlew clean assemble assembleAndroidTest
   artifacts:
     paths:
       - adblock-android-webviewapp/build/outputs/apk/release/adblock-android-webviewapp-release-unsigned.apk
       - adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk
+      # The test APK is used later in the device testing
+      - adblock-android/build/outputs/apk/androidTest/abi_all/debug/adblock-android-abi_all-debug-androidTest.apk
 
 
 build_libadblockplus-android:custom-jni:
@@ -91,6 +103,22 @@ build_libadblockplus-android:without-jni:
   script:
     - SKIP_JNI_COMPILATION=true ./gradlew clean assemble
 
+testobject_tests:
+  stage: device_tests
+  script:
+    - test -z ${TESTOBJ_PROJECT_KEY} && echo "echo TESTOBJ_PROJECT_KEY not set. Unable to run tests." && exit 1
+    - test -f /opt/ci/runner.jar || wget https://s3.amazonaws.com/saucelabs-runner/v1.8/runner.jar -O /opt/ci/runner.jar
+    # Docs for running tests on testobject:
+    # https://wiki.saucelabs.com/display/DOCS/Command+Reference+for+Sauce+Runner+for+Real+Devices
+    - java -jar /opt/ci/runner.jar espresso \
+        --test ./adblock-android/build/outputs/apk/androidTest/abi_all/debug/adblock-android-abi_all-debug-androidTest.apk \
+        --app ./adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk \
+        --testname ${CI_JOB_URL} \
+        --apikey ${TESTOBJ_PROJECT_KEY} --datacenter EU
+  artifacts:
+    reports:
+      junit: philll-adblockwebview-app-*.xml
+
 publish_to_bintray:
   <<: *common_build_all
   stage: publish
@@ -102,4 +130,3 @@ publish_to_bintray:
         echo 'Note: $DRY_RUN is currently "true", run pipeline manually and set to "false" to actually publish to bintray'
       fi
     - ./gradlew bintrayUpload -PbintrayUser=${BINTRAY_USERNAME:-unset} -PbintrayKey=${BINTRAY_KEY:-unset} -PdryRun=${DRY_RUN:-true}
-
