DPC-284 - Add automated tests on libadblockplus-android master branch

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -224,15 +224,16 @@ testobject_tests:
       junit: test-results/*/philll-adblockwebview-app-*.xml
 
 # automated regression tests using Appium
-regression_tests:
+automated_tests:
   stage: device_tests
   interruptible: true
-  retry: 1
   variables:
+    GIT_STRATEGY: "none"
     # overridable automation repo; url uses CI_JOB_TOKEN for temporary authorization
     GIT_AUTOMATION_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/sandbox/abp-webview-test-automation"
+    # demo app debug apk
     GIT_AUTOMATION_BRANCH: "master"
-    REGRESSION_TAGS: "@j1 @j2"
+    PLATFORM_VERSIONS: "10"
     # demo app debug apk
     TEST_APK: "adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk"
   script:
@@ -244,54 +245,50 @@ regression_tests:
     - cd automation
     - git checkout ${GIT_AUTOMATION_BRANCH:-master}
     # Launch an instance of gradle for each bunch of tags we want to test
+    - set +e
     - pids=""
     - |
-      for TAG in $REGRESSION_TAGS
-        do echo Starting job for tag ${TAG}
-        (nohup ./gradlew regressionParallel -P tags=${TAG} &> tag-${TAG}.log ; echo $? > result_${TAG}) &
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do export PLATFORM_VERSION
+        echo "Starting job for version ${PLATFORM_VERSION}"
+        (./gradlew automatedTesting &> platform_version-${PLATFORM_VERSION}.log ; echo $? > result_${PLATFORM_VERSION}) &
         pids="$pids $!"
       done
     - wait $pids
-    # Check the exit codes of all processes were 0
+    # Check for any failures and re-run them
     - |
-      for TAG in $REGRESSION_TAGS
-        do test $(cat result_${TAG}) = 0
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
+          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
+          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
+          ./gradlew rerunFailed
+          echo $? > result_${PLATFORM_VERSION}
+          rm -f target/rerun.txt
+        fi
+      done
+    # check the exit codes of all processes were 0
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do test $(cat result_${PLATFORM_VERSION}) = 0
       done
   after_script:
     - cd automation
     - |
-      for TAG in $REGRESSION_TAGS
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
         do
         echo "**********************************"
-        echo "Logs for tests with tag ${TAG}"
+        echo "Logs for tests with platform version ${PLATFORM_VERSION}"
         echo "**********************************"
-        cat tag-${TAG}.log
+        cat platform_version-${PLATFORM_VERSION}.log
       done
   artifacts:
+    when: always
     expire_in: 6 months
     reports:
       junit: "automation/target/cucumber-reports/*.xml"
-
-# automated functional tests using Appium
-functional_tests:
-  only:
-    - schedules
-    - web
-  stage: device_tests
-  interruptible: true
-  variables:
-    # overridable automation repo; url uses CI_JOB_TOKEN for temporary authorization
-    GIT_AUTOMATION_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/sandbox/abp-webview-test-automation"
-    # demo app debug apk
-    TEST_APK: "adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk"
-  script:
-    # TESTOBJ_PROJECT_KEY should exist, testing it
-    - test -z ${TESTOBJ_PROJECT_KEY} && echo "echo TESTOBJ_PROJECT_KEY not set. Unable to run tests." && exit 1
-    # we are not using submodules, because automation is not a part of repository functionality
-    # its rather a standalone set of scripts
-    - git clone $GIT_AUTOMATION_REPO automation
-    # `./gradlew functional` launches cucumber executor that then launches Appium client and executes entire functional tests
-    - cd automation && ./gradlew functional
+    paths:
+      - "automation/platform_version-*.log"
+      - "automation/result_*"
 
 # FilterEngine performance benchmarking and memory
 benchmark:
