Noissue - Restoring ci configuration to before master was merged on develop

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -241,16 +241,17 @@ testobject_tests:
       junit: test-results/*/philll-adblockwebview-app-*.xml
 
 # automated regression tests using Appium
-automated_tests:
+regression_tests:
   stage: device_tests
   interruptible: true
+  retry: 1
   variables:
     GIT_STRATEGY: "none"
     # overridable automation repo; url uses CI_JOB_TOKEN for temporary authorization
     GIT_AUTOMATION_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/sandbox/abp-webview-test-automation"
-    # demo app debug apk
     GIT_AUTOMATION_BRANCH: "master"
-    PLATFORM_VERSIONS: "10"
+    PLATFORM_VERSION: "10"
+    REGRESSION_TAGS: "@j1 @j2"
     # demo app debug apk
     TEST_APK: "adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk"
   script:
@@ -265,38 +266,34 @@ automated_tests:
     - set +e
     - pids=""
     - |
-      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+      for TAG in $REGRESSION_TAGS
         do export PLATFORM_VERSION
-        echo "Starting job for version ${PLATFORM_VERSION}"
-        (./gradlew automatedTesting &> platform_version-${PLATFORM_VERSION}.log ; echo $? > result_${PLATFORM_VERSION}) &
+        echo Starting job for tag ${TAG}
+        (nohup ./gradlew regressionParallel -P tags=${TAG} &> tag-${TAG}.log ; echo $? > result_${TAG}) &
         pids="$pids $!"
       done
     - wait $pids
-    # Check for any failures and re-run them
+    # gather the contents of any failed tests
+    - cat target/rerun*.txt > target/rerun.txt
+    - set -e
+    # Rerun any failed tests or check the exit codes of all processes were 0
     - |
-      for PLATFORM_VERSION in $PLATFORM_VERSIONS
-        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
-          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
-          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
-          ./gradlew rerunFailed
-          echo $? > result_${PLATFORM_VERSION}
-          rm -f target/rerun.txt
-        fi
-      done
-    # check the exit codes of all processes were 0
-    - |
-      for PLATFORM_VERSION in $PLATFORM_VERSIONS
-        do test $(cat result_${PLATFORM_VERSION}) = 0
-      done
+      if [ -s target/rerun.txt ] ; then
+        ./gradlew rerunFailed
+      else
+        for TAG in $REGRESSION_TAGS
+          do test $(cat result_${TAG}) = 0
+        done
+      fi
   after_script:
     - cd automation
     - |
-      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+      for TAG in $REGRESSION_TAGS
         do
         echo "**********************************"
-        echo "Logs for tests with platform version ${PLATFORM_VERSION}"
+        echo "Logs for tests with tag ${TAG}"
         echo "**********************************"
-        cat platform_version-${PLATFORM_VERSION}.log
+        cat tag-${TAG}.log
       done
   artifacts:
     when: always
@@ -337,7 +334,7 @@ functional_tests:
     - |
       for PLATFORM_VERSION in $PLATFORM_VERSIONS
         do export PLATFORM_VERSION
-        echo "Starting job for version ${PLATFORM_VERSION}"
+        echo Starting job for version ${PLATFORM_VERSION}
         (./gradlew functional &> platform_version-${PLATFORM_VERSION}.log ; echo $? > result_${PLATFORM_VERSION}) &
         pids="$pids $!"
       done
@@ -364,7 +361,7 @@ functional_tests:
       for PLATFORM_VERSION in $PLATFORM_VERSIONS
         do
         echo "**********************************"
-        echo "Logs for tests with platform versions ${PLATFORM_VERSION}"
+        echo "Logs for tests with platform_version ${PLATFORM_VERSION}"
         echo "**********************************"
         cat platform_version-${PLATFORM_VERSION}.log
       done
