DPC-268 - Release WebView 5.0.0
solve confilcts inside .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -144,12 +144,12 @@ build_libadblockplus-android:abp-disabled:
     # APK with adblock disabled, with a random appId
     - ./gradlew clean assemble -PadblockEnabled=false -PrandomizedAppId=true
     # Rename the APKs to avoid confusion
-    - mv adblock-android-webviewapp/build/outputs/apk/release/adblock-android-webviewapp-release-unsigned{,-ADBLOCK-DISABLED}.apk 
+    - mv adblock-android-webviewapp/build/outputs/apk/release/adblock-android-webviewapp-release-unsigned{,-ADBLOCK-DISABLED}.apk
     - mv adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug{,-ADBLOCK-DISABLED}.apk
   artifacts:
     paths:
       - adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug-ADBLOCK-DISABLED.apk
-      - adblock-android-webviewapp/build/outputs/apk/release/adblock-android-webviewapp-release-unsigned-ADBLOCK-DISABLED.apk 
+      - adblock-android-webviewapp/build/outputs/apk/release/adblock-android-webviewapp-release-unsigned-ADBLOCK-DISABLED.apk
   when: manual
 
 # The remaining build_* jobs are only built on rc branches
@@ -241,17 +241,16 @@ testobject_tests:
       junit: test-results/*/philll-adblockwebview-app-*.xml
 
 # automated regression tests using Appium
-regression_tests:
+automated_tests:
   stage: device_tests
   interruptible: true
-  retry: 1
   variables:
     GIT_STRATEGY: "none"
     # overridable automation repo; url uses CI_JOB_TOKEN for temporary authorization
     GIT_AUTOMATION_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/sandbox/abp-webview-test-automation"
+    # demo app debug apk
     GIT_AUTOMATION_BRANCH: "master"
-    PLATFORM_VERSION: "10"
-    REGRESSION_TAGS: "@j1 @j2"
+    PLATFORM_VERSIONS: "10"
     # demo app debug apk
     TEST_APK: "adblock-android-webviewapp/build/outputs/apk/debug/adblock-android-webviewapp-debug.apk"
   script:
@@ -266,34 +265,38 @@ regression_tests:
     - set +e
     - pids=""
     - |
-      for TAG in $REGRESSION_TAGS
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
         do export PLATFORM_VERSION
-        echo Starting job for tag ${TAG}
-        (nohup ./gradlew regressionParallel -P tags=${TAG} &> tag-${TAG}.log ; echo $? > result_${TAG}) &
+        echo "Starting job for version ${PLATFORM_VERSION}"
+        (./gradlew automatedTesting &> platform_version-${PLATFORM_VERSION}.log ; echo $? > result_${PLATFORM_VERSION}) &
         pids="$pids $!"
       done
     - wait $pids
-    # gather the contents of any failed tests
-    - cat target/rerun*.txt > target/rerun.txt
-    - set -e
-    # Rerun any failed tests or check the exit codes of all processes were 0
+    # Check for any failures and re-run them
     - |
-      if [ -s target/rerun.txt ] ; then
-        ./gradlew rerunFailed
-      else
-        for TAG in $REGRESSION_TAGS
-          do test $(cat result_${TAG}) = 0
-        done
-      fi
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
+          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
+          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
+          ./gradlew rerunFailed
+          echo $? > result_${PLATFORM_VERSION}
+          rm -f target/rerun.txt
+        fi
+      done
+    # check the exit codes of all processes were 0
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do test $(cat result_${PLATFORM_VERSION}) = 0
+      done
   after_script:
     - cd automation
     - |
-      for TAG in $REGRESSION_TAGS
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
         do
         echo "**********************************"
-        echo "Logs for tests with tag ${TAG}"
+        echo "Logs for tests with platform version ${PLATFORM_VERSION}"
         echo "**********************************"
-        cat tag-${TAG}.log
+        cat platform_version-${PLATFORM_VERSION}.log
       done
   artifacts:
     when: always
